server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: bank-api
  # database configuration
  datasource:
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  # jpa configuration
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms

logging:
  level:
    kr.co.won.bank: INFO
    io.github.resilience4j: DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html # UI에 대한 경로
    operations-sorter: method # 문서를 보여줄 때 정렬 순서
  packages-to-scan: kr.co.won.bank.api # swagger를 가져다 만들어줄 package의 경로
  paths-to-match: /api/** # /api로 시작하는 부분만 보여주기 위한 설정
