server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: bank-api


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html # UI에 대한 경로
    operations-sorter: method # 문서를 보여줄 때 정렬 순서
  packages-to-scan: kr.co.won.bank.api # swagger를 가져다 만들어줄 package의 경로
  paths-to-match: /api/** # /api로 시작하는 부분만 보여주기 위한 설정
