# github action

name: Java CI with Gradle

# action on define branch and pull_request branch
on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

# working action job define
jobs:
  checkout:
    name: CheckOut Repository Setting Java Environment
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_sha.outputs.sha }}
    steps: # job step define
      - name: Checkout Code -> repository
        uses: actions/checkout@v4
      - name: Save Commit SHA
        id: get_sha
        run: echo "sha=${{github.sha}}" >> "$GITHUB_OUTPUT"
  # Build Job
  set-up-env:
    name: Gradle Environment Setting
    runs-on: ubuntu-latest
    needs: checkout # depend on
    steps:
      - uses: actions/checkout@v4
      # Setting Java Version
      - name: Setting Java Environment Version 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle
      # Setting Gradle
      - name: Setting Gradle
        uses: gradle/actions/setup-gradle@v4
      #
      - name: Gradle Execute Permission for gradlew
        run: chmod +x ./gradlew
  # testing run
  run-testing:
    needs: set-up-env
    runs-on: ubuntu-latest
    # Job Step define
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Testing Environment Setting
      - name: Testing Environment Set Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
          cache: gradle
      - name: Testing Environment Set Gradle
        run: chmod +x ./gradlew
      # Run Testing
      - name: Gradle Tests
        run: ./gradlew test
  # Packaging Application
